running all tests in one command

diff --git a/bin/test b/bin/test
--- a/bin/test
+++ b/bin/test
@@ -1,2 +1,7 @@
 #! /bin/bash
-echo '#todo test'
+npm test > /dev/null
+if [[ $? == 1 ]]; then
+  echo "failing tests" 
+else
+  echo "passed"
+fi
